service: "X-Cell"

provider:
    name: aws
    runtime: nodejs18.x
    stage: dev
    region: ap-south-1
    apiGateway:
        binaryMediaTypes:
            - "multipart/form-data"
    package:
    excludeDevDependencies: true
    exclude:
        - .git/**
        - .vscode/**
        - venv/**
functions:
    app:
        handler: server.handler
        name: X-Cell-manish-tanwar
        events:
            - http:
                  path: /
                  method: ANY
                  cors: true
            - http:
                  path: /{proxy+}
                  method: ANY
                  cors: true

# plugins:
#     - serverless-offline
    # - serverless-event-body-option
