const express = require("express");
const router = express.Router();
const orderController = require("../controllers/order.controller");
const { authJwt, objectId } = require("../middlewares");
const { upload, upload1 } = require("../utils/upload");
router.get("/orders", orderController.getAllOrders);
router.get("/ordersforSubAdmin", [authJwt.isAdmin], orderController.getAllOrdersforSubAdmin);
router.get("/countordersforSubAdmin", [authJwt.isAdmin], orderController.getOrderCountsByMonthforSubAdmin);
router.post("/orders", orderController.createOrder);
router.get("/orders/:id", orderController.getOrderById);
router.patch("/admin/orders/:id", [authJwt.isAdmin, objectId.validId], orderController.updateOrder);
router.delete("/admin/orders/:id", [authJwt.isAdmin, objectId.validId], orderController.deleteOrder);
router.get("/download", orderController.download);
router.post("/upload", upload1.single("file"), orderController.import);
router.get("/countorders", orderController.getOrderCountsByMonth);
router.post("/order-add", orderController.addOrder);
module.exports = router;
